#! /usr/bin/env sh

# [ Misc ]
sudo pacman -S starship fzf tmux fastfetch feh gimp xclip mc xorg-xinput flameshot dpkg btop less numlockx mandoc

# [ Rust ]
sudo pacman -S rustup cargo
rustup override set stable
rustup update stable

# [ Paru ]
sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si

# [ Bluetooth ]
sudo pacman -S bluez bluez-utils
sudo systemctl enable -now bluetooth
paru -S blutuith

# [ Alacritty ]
sudo pacman -S cmake freetype2 fontconfig pkg-config make libxcb libxkbcommon python  # Deps

cd /tmp
git clone https://github.com/alacritty/alacritty.git
cd alacritty
cargo build --release

sudo pacman -S scdoc
sudo mkdir -p /usr/local/share/man/man1
sudo mkdir -p /usr/local/share/man/man5
scdoc < extra/man/alacritty.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
scdoc < extra/man/alacritty-msg.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty-msg.1.gz > /dev/null
scdoc < extra/man/alacritty.5.scd | gzip -c | sudo tee /usr/local/share/man/man5/alacritty.5.gz > /dev/null
scdoc < extra/man/alacritty-bindings.5.scd | gzip -c | sudo tee /usr/local/share/man/man5/alacritty-bindings.5.gz > /dev/null
mkdir -p ~/.bash_completion
cp extra/completions/alacritty.bash ~/.bash_completion/alacritty
echo "source ~/.bash_completion/alacritty" >> ~/.bashrc
sudo cp target/release/alacritty /usr/local/bin # or anywhere else in $PATH
sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
sudo desktop-file-install extra/linux/Alacritty.desktop
sudo update-desktop-database

mkdir ~/.config/alacritty
curl -LO --output-dir ~/.config/alacritty https://github.com/catppuccin/alacritty/raw/main/catppuccin-frappe.toml


# [ Nvim ]
cd ~/.config
sudo pacman -S neovim ripgrep fzf fd ctags deno
git clone https://github.com/mrjeem/nvim-config nvim

# [ Bash ]
# TODO: git clone the .custom_env & starship conf
sudo pacman -S zoxide

# [ Fonts ]
# TODO: Downlaod and copy the fonts to ~/.local/share/fonts then:
fc-cache -vf

# [ i3 ]
# TODO: Clone the config
mkdir ~/.config/i3status
sudo pcaman -S i3lock

# [ NetworkManager ]
sudo pacman -S networkmanager networkmanager-openvpn
sudo systemctl enable --now nmcli
sudo systemctl enable --now NetworkManager

nmcli device wifi list
nmcli device wifi connect <SSID> password <PASSWORD> hidden <yes|no>

nmcli connection import type openvpn file ~/.config/ovpn/Anima.ovpn
# Modify these in /etc/NetworkManager/system-connections/Anima.nmconnection
#  [ vpn ]
#  password-flags=0
#  username=username
#  [vpn-secrets]
#  password=password
#  sudo nmcli connection reload
#  nmcli connection up Anima

# [ Mounts ]
sudo pacman -S ntfs-3g fuse

sudo mkdir /mnt/usb
sudo mount sdb /mnt/usb/
sudo mount /dev/sdb /mnt/usb/

sudo mkdir /mnt/win_c
sudo mkdir /mnt/win_d
sudo mount -t ntfs-3g /dev/sda1 /mnt/win_d
sudo mount -t ntfs-3g /dev/nvme0n1p3 /mnt/win_c

# [ Bat ]
sudo pacman -S bat
mkdir -p ~/.config/bat/themes
mkdir -p "$(bat --config-dir)/themes"
wget -P "$(bat --config-dir)/themes" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Frappe.tmTheme
touch ~/.config/bat/config
echo --theme="Catppuccin Frappe" >> ~/.config/bat/config

# [ LightDM ]
sudo pacman -S lightdm-webkit2-greeter
sudo systemctl restart lightdm

# [Input leap]
sudo pacman -S qt6-5compat
paru -S input-leap-git

# [ Os Prober]
sudo pacman -S os-prober
# TODO: enable os-prober in /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg

# [ Avahi ]
# For DNS resolution
sudo pacman -S avahi
sudo systemctl enable --now avahi-daemon
